config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: 'home#index' 
  resources :users
  resources :recipes do
    resource :likes, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
  
  validates_uniqueness_of :recipe_id, scope: :user_id
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  #attachment :image
  mount_uploader :image_id, ImageUploader
  
  has_many :likes, dependent: :destroy
  
  with_options presence: true do
    validates :recipe_title
    validates :recipe_detail
    validates :image_id
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  #attachment :profile_image
  mount_uploader :profile_image_id, ImageUploader
  
  has_many :recipes, dependent: :destroy
  has_many :likes, dependent: :destroy
  
  validates :username, presence: true
  
  def likes_already_exits?(recipe)
    self.likes.exists?(recipe_id: recipe.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #もしdeviseのコントローラーの事なら全てのアクションの前にメソッドを読み込む
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    user_path(current_user)
  end
  
  def after_sign_up_path_for(resource)
    user_path(current_user)
  end
  
  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end
  
  private
  def configure_permitted_parameters
    #新規登録機能について
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.create(recipe_id: params[:recipe_id])
    @like.save
    redirect_back(fallback_location: root_path)
  end
  
  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    like = current_user.likes.find_by(recipe_id: @recipe.id)
    like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end
  
  def create
    @recipe = current_user.recipes.build(recipe_params)
    @recipe.user_id = current_user.id
    if @recipe.save
      redirect_to recipe_path(@recipe), notice: "レシピを投稿しました。"
    else
      render :new
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
    if @recipe.user != current_user
      redirect_to recipes_path, alert: "不正なアクセスです。"
    end
  end
  
  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      redirect_to recipe_path(@recipe), notice: "レシピを更新しました。"
    else
      render :edit
    end
  end
  
  def destroy
    recipe = Recipe.find(params[:id])
    recipe.destroy
    redirect_to user_path(recipe.user), notice: "レシピを削除しました。"
  end
  
  private
  def recipe_params
    params.require(:recipe).permit(:recipe_title, :recipe_detail, :image_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user), alert: "不正なアクセスです。"
    end
  end
  
  def update 
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "ユーザー情報を更新しました。"
    else
      render :edit
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:username, :email, :profile, :profile_image_id)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<section class="section main-image">
  <div class="container">
    <div class="has-text-centered home-contents">
      <h1 class="mb-5 is-size-2" style="font-family: cursive">Let's make great memories!</h1>
      <p class="mb-5 is-size-5">おすすめなレシピを共有しませんか？美味しい料理で良い一日を。</p>
      <div class="">
        <%= link_to "ログイン", new_user_session_path, class: "button is-link is-outlined mr-5" %>
        <%= link_to "新規登録", new_user_registration_path, class: "button is-link is-outlined ml-5" %>
      </div>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= favicon_link_tag('cookbook_icon.png') %>
    <script src="https://kit.fontawesome.com/f1434e723f.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav id="app" class="navbar has-background-color" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <%= link_to root_path, class: "navbar-item ml-2" do %>
          <%= image_tag "cookbook_icon.png" %>
          <h1 class="title is-4 ml-3" style="font-family: cursive">RECIPEAPP</h1>
        <% end %>
        
        <div role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample" @click="isOpen = !isOpen" v-bind:class="{'is-active': isOpen}">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </div>
      </div>
      
      <% if user_signed_in? %>
        <div id="navbarBasicExample" class="navbar-menu" v-bind:class="{'is-active': isOpen}">
          <div class="navbar-item">
            <%= link_to "レシピ一覧", recipes_path, class: "button is-ghost has-text-black" %>
          </div>
          <div class="navbar-item">
            <%= link_to "投稿者一覧", users_path, class: "button is-ghost has-text-black" %>
          </div>
          
          <div class="navbar-end"> 
            <div class="navbar-item">
              <%= link_to "レシピ投稿", new_recipe_path, class: "button is-ghost has-text-black" %>
            </div>
            <div class="navbar-item">
              <%= link_to "マイページ", user_path(current_user), class: "button is-ghost has-text-black" %>
            </div>
            <div class="navbar-item">
              <%= link_to "ログアウト", destroy_user_session_path, class: "button is-ghost has-text-black" %>
            </div>
          </div>
        </div>
      <% else %>
        <div id="navbarBasicExample" class="navbar-menu" v-bind:class="{'is-active': isOpen}">
          <div class="navbar-end ">
            <div class="navbar-item">
              <%= link_to "投稿者一覧", users_path, class: "button is-ghost has-text-black" %>
            </div>
            <div class="navbar-item">
              <%= link_to "ログイン", new_user_session_path, class: "button is-ghost has-text-black" %>
            </div>
            <div class="navbar-item">
              <%= link_to "新規登録", new_user_registration_path, class: "button is-ghost has-text-black" %>
            </div>  
          </div>
        </div>
      <% end %>
    </nav>
    
    <% if flash[:notice] %>
      <div class="notification is-warning has-text-centered is-size-5">
        <div class="columns is-centered">
          <div class="column is-5">
            <p class="notice">
              <%= notice %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
    
    <% if flash[:alert] %>
      <div class="notification is-danger has-text-centered is-size-5">
        <div class="columns is-centered">
          <div class="column is-5">
            <p class="alert">
              <%= alert %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
    
    <%= yield %> 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.5.16/vue.min.js"></script>
    <script type="module">
      window.addEventListener('load',function(){
        var app = new Vue({
          el: '#app',
          data: {
              isOpen: false
          }
        });
      });
    </script>
  </body>
  
  <footer class="footer">
    <div class="container has-text-centered">
      <p>&copy;Copyright RecipeApp. SHUREN. 2022.</p>
    </div>
  </footer>
</html>

app/views/recipes/edit.html.erb
<% if @recipe.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @recipe.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered has-text-centered">
      <h1 class="title">レシピ編集</h1>
    </div>
    </br>
    <div class="columns is-centered has-text-centered">
      <p>以下の任意の項目にご記入の上、「更新」ボタンを押してください。</p>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-5">
        <%= form_for @recipe do |f| %>
          <div class="box">
            <div class="field">
              <%= f.label :recipe_title, "レシピ名", class: "label" %>
              <p class="control">
                <%= f.text_field :recipe_title, class: "input is-link" %>
              </p>
            </div>
            <div class="field">
              <%= f.label :recipe_detail, "レシピ内容", class: "label" %>
              <p class="control">
                <%= f.text_area :recipe_detail, class: "textarea is-link" %>
              </p>
            </div>
            <div class="field">
              <%= f.label :image_id, "写真", class: "label" %>
              <p class="control">
                <%= f.file_field :image_id %>
              </p>
            </div>
            <div class="has-text-centered">
              <%= f.submit '更新', class: "button is-link pl-6 pr-6" %>
            </div>
          </box>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/recipes/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-centered has-text-centered">
      <h1 class="title">レシピ一覧</h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @recipes.each do |recipe| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-content">
              <div class="card-image">
                <figure class="image img-container-recipe-index">
                  <%= link_to recipe_path(recipe) do %>
                    <%= image_tag recipe.image_id.to_s, fallback: "no-image.png" %>
                  <% end %>
                </figure>
              </div>
  
              <div class="media mt-5">
                <figure class="media-left">
                  <div class="image is-48x48">
                    <%= image_tag recipe.user.profile_image_id.to_s, fallback: "image_profile.png", class: "is-rounded" %>
                  </div>
                </figure>
                <div class="media-content">
                  <div class="content">
                    <div class="pt-2 parent">
                      <%= link_to recipe.user.username, user_path(recipe.user), class: "title is-4 has-text-link" %>
                      <div class="is-size-5">
                        <% if current_user.likes_already_exits?(recipe) %>
                          <%= button_to recipe_likes_path(recipe), :method => :delete, class: "link-style link-style-pink" do %>
                            <i class="fas fa-heart"></i>
                            <span class="black"><%= recipe.likes.count %></span>
                          <% end %>
                         
                        <% else %>
                          <%= button_to recipe_likes_path(recipe), :method => :post, class: "link-style" do %>
                            <i class="far fa-heart"></i>
                            <%= recipe.likes.count %>
                          <% end %>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="content ml-1 .is-marginless">
                <time>
                  <%= recipe.updated_at.strftime("%Y-%m-%d %H:%M") %>
                  <span>更新</span>
                </time>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/recipes/new.html.erb
<% if @recipe.errors.any? %>
  <div class="notification is-danger has-text-centered">
    <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @recipe.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered has-text-centered">
      <h1 class="title">レシピ作成</h1>
    </div>
    </br>
    <div class="columns is-centered has-text-centered">
      <p>以下の任意の項目にご記入の上、「投稿」ボタンを押してください。</p>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-5">
        <%= form_for @recipe do |f| %>
          <div class="box">
            <div class="field">
              <%= f.label :recipe_title, "レシピ名", class: "label required" %>
              <p class="control">
                <%= f.text_field :recipe_title, class: "input is-link" %>
              </p>
            </div>
            <div class="field">
              <%= f.label :recipe_detail, "レシピ内容", class: "label required" %>
              <p class="control">
                <%= f.text_area :recipe_detail, class: "textarea is-link" %>
              </p>
            </div>
            <div class="field">
              <%= f.label :image_id, "レシピ画像", class: "label required" %>
              <p class="control">
                <%= f.file_field :image_id %>
              </p>
            </div>
            <div class="has-text-centered">
              <%= f.submit '投稿', class: "button is-link pl-6 pr-6" %>
            </div>
          </box>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/recipes/show.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-centered has-text-centered">
      <h1 class="title">レシピ内容</h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-5">
        <div class="card">
          <div class="card-image">
            <figure class="image img-container-recipe-show">
              <%= image_tag @recipe.image_id.to_s %>
            </figure>
          </div>
          <div class="card-content">
            <div class="media">
              <div class="media-content">
                <div class="title is-size-5">
                  <%= @recipe.recipe_title %>
                </div>
              </div>
            </div>
            <div class="content">
              <table class="table">
                <tr>
                  <th>レシピ内容</th>
                </tr>
                <tr>
                  <td>
                    <%= simple_format @recipe.recipe_detail %>
                  </td>
                </tr>
              </table>
              
              <div class="parent">
                <time class="ml-2 pt-1">
                  <%= @recipe.updated_at.strftime("%Y-%m-%d %H:%M") %>
                  <span>更新</span>
                </time>
                <div class="is-size-5">
                  <% if current_user.likes_already_exits?(@recipe) %>
                    <%= button_to recipe_likes_path(@recipe), :method => :delete, class: "link-style link-style-pink" do %>
                      <i class="fas fa-heart"></i>
                      <span class="black"><%= @recipe.likes.count %></span>
                    <% end %>
                  <% else %>
                    <%= button_to recipe_likes_path(@recipe), :method => :post, class: "link-style" do %>
                      <i class="far fa-heart"></i>
                      <%= @recipe.likes.count %>
                    <% end %>
                  <% end %>
                </div>
              </div>
              <div class="parent-1 mt-5">
                <% if @recipe.user.id == current_user.id %>
                  <%= link_to "編集", edit_recipe_path(@recipe), class: "button is-link is-outlined" %>
                  <%= button_to "削除", recipe_path(@recipe), :method => :delete, data: {confirm: "本当にレシピを削除しますか？"}, class: "button is-link is-outlined ml-4 link-style-delete1" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/edit.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-centered has-text-centered">
      <h1 class="title">ユーザー編集</h1>
    </div>
    </br>
    <div class="columns is-centered has-text-centered">
      <p>以下の任意の項目にご記入の上、「更新」ボタンを押してください。</p>
    </div>
  </div>
</section>

<% if @user.errors.any? %>
  <div class="notification is-danger has-text-centered">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-5">
        <%= form_for @user do |f| %>
          <div class="box">
            <div class="field">
              <%= f.label :username, "ユーザー名", class: "label" %>
              <p class="control has-icons-left">
                <%= f.text_field :username, class: "input is-link" %>
                <span class="icon is-small is-left"> 
                  <i class="fas fa-user"></i>
                </span>
              </p>
            </div>
            
            <div class="field">
              <%= f.label :email, "メールアドレス", class: "label" %>
              <p class="control has-icons-left">
                <%= f.email_field :email, class: "input is-link" %>
                <span class="icon is-small is-left"> 
                  <i class="fas fa-envelope"></i>
                </span>
              </p>
            </div>
            
            <div class="field">
              <%= f.label :profile, "プロフィール", class: "label" %>
              <p class="control">
                <%= f.text_area :profile, class: "textarea is-link" %>
              </p>
            </div>
            
            <div class="field">
              <%= f.label :profile_image_id, "プロフィール画像", class: "label" %>
              <p class="control">
                <%= f.file_field :profile_image_id %>
              </p>
            </div>
            
            <div class="has-text-centered">
              <%= f.submit "更新", class: "button is-link pl-6 pr-6" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </container>
</section>

app/views/users/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-centered has-text-centered">
      <h1 class="title">投稿者一覧</h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @users.each do |user| %>
        <div class="column is-3">
          <div class="card">
            <div class="card-content">
              <div class="card-image">
                <figure class="image img-container-user-index">
                  <%= link_to user_path(user) do %>
                    <%= image_tag user.profile_image_id.to_s %>
                  <% end %>
                </figure>
              </div>
           
              <div class="media mt-5">
                <div class="media-content">
                  <div class="title is-4 ml-1">
                    <%= link_to user.username, user_path(user) %>
                  </div>
                </div>
              </div>
              <div class="content ml-1">
                投稿数：<%= user.recipes.count %></br>
                いいねされた数：
                <% user_recipes = user.recipes %> 
                <% likes_count = 0 %>
                <% user_recipes.each do |recipe| %>
                  <% likes_count += recipe.likes.count %>
                <% end %>
                <%= likes_count %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-centered has-text-centered">
      <h1 class="title">マイページ</h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <div class="box">
          <div class="columns is-centered">
            <div class="column is-9">
              <figure class="image is-64x64">
                <%= image_tag @user.profile_image_id.to_s, class: "is-rounded" %>
              </figure>
              <div class="ml-1 mt-3 is-size-5">
                <strong class="mr-2"><%= @user.username %></strong>
                <% if @user.id == current_user.id %>
                  <%= @user.email %>
                <% end %>
              </div>
              <div class=" ml-1 mt-3 is-size-6">
                <%= @user.profile %>
              </div>
            </div>
            <% if @user.id == current_user.id %>
              <div class="is-size-5 mt-5">
                <%= link_to "編集", edit_user_path(@user), class: "button is-link is-outlined mr-2 ml-2" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @user.recipes.each do |recipe| %>
        <div class="column is-3">
          <div class="card">
            <div class="card-image">
              <figure class="image  img-container-user-show">
                <%= link_to recipe_path(recipe) do %>
                  <%= image_tag recipe.image_id.to_s, fallback: "no-image.png" %>
                <% end %>
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <%= link_to recipe_path(recipe), class: "panel-block" do %>
                    <span class="panel-icon">
                      <i class="fas fa-book"></i>
                    </span>
                    このレシピを見る  
                  <% end %>
                  <% if @user.id == current_user.id %>
                    <%= link_to edit_recipe_path(recipe), class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-edit"></i>
                      </span>
                      このレシピを編集する
                    <% end %>
                    <%= button_to recipe_path(recipe), :method => :delete, data: {confirm: "本当にレシピを削除しますか？"}, class: "panel-block link-style-delete" do %>
                      <span class="panel-icon">
                        <i class="fas fa-trash"></i>
                      </span>
                      このレシピを削除する
                    <% end %>
                  <% end %>
                </div>
              </div>
              <div class="content ml-3">
                <time>
                  <%= recipe.updated_at.strftime("%Y-%m-%d %H:%M") %>
                  <span>更新</span>
                </time>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>